services:
  sveltekit:
    image: jkeil/sveltekit-castercurse:latest
    restart: always
    env_file: .env
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot_data/conf:/etc/letsencrypt
      - ./data/certbot_data/www:/var/www/certbot
    depends_on:
      - sveltekit
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot_data/conf:/etc/letsencrypt
      - ./data/certbot_data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge
