# .github/workflows/deploy.yml

name: Build and Deploy SvelteKit App

on:
  push:
    branches: [ "main" ] # Runs when you push to the main branch

env:
  # IMPORTANT: Change this to your Docker Hub username and image name
  DOCKER_IMAGE: jkeil/sveltekit-castercurse

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          # This section passes your ARGs to the Dockerfile
          build-args: |
            PUBLIC_ORIGIN=${{ secrets.PUBLIC_ORIGIN }}
            PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
            PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}
            PUBLIC_TWITCH_CLIENT_ID=${{ secrets.PUBLIC_TWITCH_CLIENT_ID }}
            PUBLIC_TWITCH_AUTH_CALLBACK=${{ secrets.PUBLIC_TWITCH_AUTH_CALLBACK }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Castercurse
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            docker compose up -d --no-deps sveltekit
            docker image prune -f